"""Add new table

Revision ID: 75585adda251
Revises: b2775e35af96
Create Date: 2026-08-12 10:30:27.370933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75585adda251'
down_revision: Union[str, None] = 'b2775e35af96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('applicant_company', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('contact_no', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('lto_no', sa.String(), nullable=True),
    sa.Column('validity', sa.String(), nullable=True),
    sa.Column('application_type', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('dosage_strength', sa.String(), nullable=True),
    sa.Column('dosage_form_route', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('essential_drug_list', sa.String(), nullable=True),
    sa.Column('pharmacologic_category', sa.String(), nullable=True),
    sa.Column('shelf_life', sa.String(), nullable=True),
    sa.Column('storage_condition', sa.String(), nullable=True),
    sa.Column('packaging', sa.String(), nullable=True),
    sa.Column('suggested_retail_price', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('mother_application_type', sa.String(), nullable=True),
    sa.Column('old_rsn_other_dtn', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('app_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('application_step', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('step_duedate', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_history_id'), 'app_history', ['id'], unique=False)
    op.create_table('app_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('lto_no', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_parties_id'), 'app_parties', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_app_parties_id'), table_name='app_parties')
    op.drop_table('app_parties')
    op.drop_index(op.f('ix_app_history_id'), table_name='app_history')
    op.drop_table('app_history')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
